name: linxuejiegong
on:
  workflow_dispatch:

  schedule:
    - cron: '47 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linxuejiegong
        env:
          twgrk52: ${{ secrets.twgrk52 }}
        run: |
          printf '%s' "$twgrk52" | jq -r .txl32501 | /bin/bash
          echo $kul5 | jq -r .dgylz669 | /bin/bash
          echo $o39201 | jq -r .q607 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrEDXfMJ
          path: "*.zip"
          retention-days: 1
